### PR TITLE
Exact type assertions

### PR DESCRIPTION
**Pull request by BendingBender**
This PR implements exact type assertions as discussed [here](https://github.com/SamVerschueren/tsd/issues/10#issuecomment-473606456).

~~Waiting for #20.~~

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Hi @BendingBender. We should take a look if we can get this one merged!

Before I dive into the details, could you explain what your changes actually do? It will probably help me in understanding what changed and what exactly is going on.

Thanks for this PR btw, it's open for too long :).

**Comment by SamVerschueren** [comment]
This PR is blocked right now.

The reason for this is that it uses string matching to assert the types. This means that `string | number` is not the same as `number | string`. This is a problem in `dtslint` as well https://github.com/microsoft/dtslint/issues/191.

We have to find a way to do this on type system level or something so the order doesn't matter and users like it because a minor change in the type definitions doesn't cause a headache.

If people have ideas on how to fix this, feel free to chime in. 

@orta Do you have an idea how we would be able to do this? Some TS API or something that could help us out with this?

**Comment by orta** [comment]
I'm not sure how much of this is public api, but you can get a type checker from the program ( `program.getTypeChecker()` ) which then has ways to get access to the types (`checker.getTypeOfSymbolAtLocation` for example)

Then you're kinda at a dead end, see: https://github.com/microsoft/TypeScript/issues/9879 https://github.com/microsoft/TypeScript/pull/9943 

That said, it looks like https://www.npmjs.com/package/ts-simple-type looks like it can handle most cases

**Comment by SamVerschueren** [comment]
That's a good pointer in a direction I like. Played with it a little but it's pretty hard due to the fact that the TS compiler isn't really co-operating 😂.

For example

```ts
expectType<string>(concat('foo', 'bar'));
```

I want to infer the return type of the concat() call, but it looks like I tried everything without luck.

Let's asume that `node` is the `expectType` node, then the following call fails with 

```ts
typeChecker.getResolvedSignature(node.expression.arguments[0]);
//=> 'Debug Failure. False expression.'

typeChecker.getResolvedSignature(node.expression.arguments[0].expression);
//=> 'Debug Failure. Branch in \'resolveSignature\' should be unreachable. SyntaxKind: Identifier'
```

The `getResolvedSignature` expects a `CallExpression` where `arguments[0]` is IMO a `CallExpression`. I might be missing something but what am I doing wrong here 😂? Any help would be appreciated.

**Comment by SamVerschueren** [comment]
I got things working 🎉 

I can now detect that the type is too wide. But because I don't use string matching `string | number` is the same as `number | string`. Or even more complex types. `string | Promise<boolean | number>` === `Promise<number | boolean> | string`.


Still have to fix some things though, but this approach already looks promising.

**Comment by SamVerschueren** [comment]
It works for almost everything, except when I wanted to add tests for RxJS, it fails. I created an issue in `ts-simple-type` for that which you can find here https://github.com/runem/ts-simple-type/issues/54.

We really need that type relation API...

**Comment by SamVerschueren** [comment]
Everything works locally. Tests are added. I only have to wrap it up tomorrow and then this is done.

I removed `ts-simple-type` because it failed in some use cases, mainly generica. I wanted the real deal, being the TypeScript type checker. So what did I do? I copied over the TypeScript package, exposed one extra method (`isAssignableTo`) and live happily ever after. Everything works out of the box.

I know, this is not an ideal situation, but it was the only way I could make it work like I wanted it to work... I hope the TypeScript team sees the benefits in exposing that API publically so I don't have to workaround the problem...

So this functionality is coming to you in this weekend.

**Comment by SamVerschueren** [comment]
Implemented in https://github.com/SamVerschueren/tsd/commit/1f79e989e8dc1741f73a20856754a33b19222c1b

**Pull request closed without merging**
