### PR TITLE
Add `expectDocCommentIncludes` assertion

### PR DESCRIPTION
**Pull request by tommy-mitchell**
Adds an assertion to check the documentation comment of a given expression:

```ts
/** FooBar */
const foo = 'bar';

expectDocComment<'FooBar'>(foo);
```

Fails if the type parameter does not exist, is not a string literal, or does not match the given expression's doc comment.

In one project, I have a function that takes a set of user-defined extension functions and maps them onto the built-ins. `expectDocComment` can help ensure that the type hinting for the user-defined extensions are mapped correctly.

### CODE REVIEW

**Comment by sindresorhus** [comment]
It doesn't really make sense to me that it's matching the whole doc comment. That would make the assertion huge. I think something like `expectDocumentationCommentToContain()` would be more practical. So you can assert that the doc comment contains a certain substring.

**Comment by tommy-mitchell** [comment]
I agree, I wanted to see what your thoughts were before making the match non-exact. I went with `expectDocCommentIncludes` since it's less verbose and matches `string.includes()`.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by tommy-mitchell** [comment]
Merged.

**Pull request merged**
