### PR TITLE
Update to TypeScript 4.1.2

### PR DESCRIPTION
**Pull request by L2jLiga**

### CODE REVIEW

**Comment by kibertoad** [comment]
Probably can be replaced with final 4.1.2 release?..

**Comment by L2jLiga** [comment]
Yes, since it released

**Comment by L2jLiga** [comment]
Done, also created separated PR with "How to update TypeScript version" README section added: https://github.com/SamVerschueren/tsd/pull/88

**Comment by SamVerschueren** [comment]
Sorry, I didn't notice your PR until I did it myself 🙏 .

Fixed by 4c8524ded11c6bd1fb02ef2fa8969b02a47eaec1

**Comment by L2jLiga** [comment]
Any plans to release this soon?

**Comment by SamVerschueren** [comment]
Released it 🎉 https://github.com/SamVerschueren/tsd/releases/tag/v0.14.0

Actually wanted to wait for #74 but figured people are waiting for this so could as well just create another after that PR lands.

**Pull request closed without merging**
