### PR TITLE
feat(`diagnostic`): add missing error codes

### LINKED ISSUE #143: Not catching readonly error
I would expect the "only permits reading" error to be caught by the test framework and not reported when running `tsd`, but instead I get notified that no error was found *and* that I was assigning to an index signature only permitting reading:

```ts
export type KeysStrictReadonly = {
    readonly [type: string]: readonly string[];
};
```

```ts
import { expectError } from 'tsd';
import { KeysStrictReadonly } from "../lib/index.js";

expectError(() => {
    const erring: KeysStrictReadonly = {
        TestInterface1: ["left", "right"]
    };
    erring.TestInterface1 = ["badAttemptOverwrite"];
});
```

### LINKED ISSUE #170: `expectError` finds none, and finds an error... for the same invocation.
This one is weird.

`expectError` is not finding an error & finding an error for the same check.

```
  test/typings/test-d/update.test-d.ts:42:43
  ✖  42:2   Expected an error, but found none.                                                                                                                                                                                                                                                                                                                                                                                                                                          
  ✖  42:43  Argument of type { readonly first_name: "John"; readonly dinosaurs?: string[]; } is not assignable to parameter of type PickWith<{ readonly first_name: "John"; readonly dinosaurs?: string[]; }, MutationObject<From<Database, "person">, "person", "person">> with exactOptionalPropertyTypes: true. Consider adding undefined to the types of the target's properties.
  Types of property dinosaurs are incompatible.
    Type string[] is not assignable to type never.  

  2 errors
```

https://github.com/igalklebanov/kysely/blob/tighten-input-objects/test/typings/test-d/update.test-d.ts

also happens after updating tsd to 0.24.1.

removing `exactOptionalPropertyTypes: true` from `test/typings/tsconfig.json` makes it pass all tests.

### PR DESCRIPTION
**Pull request by tommy-mitchell**
Fixes #170. Fixes #143.

Adds missing diagnostic codes:

- `ts2375`, `ts2379`, and `ts2412`, which occur when [`exactOptionalPropertyTypes`](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) is set to `true` in `tsconfig.json`.
- `ts2542`, which occurs when attempting to modify a readonly key in an object.

---

Related, I think it's worth improving the error reporting when `expectError` fails. Currently, it reports 

```
Expected an error, but found none.
```

even if another error is reported for the same invocation (i.e., `tsd` doesn't support that diagnostic code). We could change it to:

```
Expected an error, but found none. tsd may not currently support this error code, consider creating an issue on GitHub.
```

I used the following snippet in `compiler.ts` to confirm which `DiagnosticCode` to add[^1]:

```ts
if (ignoreDiagnosticResult === 'preserve') {
  console.log(diagnostic.code);
}
```

I think it would be worthwhile to either report the codes of all diagnostics (potentionally in a `--verbose` mode?), or at the very least in the `expectError` message:

```ts
let message = 'Expected an error, but found none.';

if (diagnostic.code) {
  message += ` tsd may not currently support \`ts${diagnostic.code}\`, consider creating an issue on GitHub.`;
}
```

[^1]: Full list [here](https://github.com/microsoft/TypeScript/blob/main/src/compiler/diagnosticMessages.json).

### CODE REVIEW

**Comment by tommy-mitchell** [comment]
Perhaps users could set additional diagnostic codes in their `tsd` config, to let their tests still pass if that code isn't in our list.

**Comment by tommy-mitchell** [comment]
Added `ts2542` to fix #143.

**Comment by sindresorhus** [comment]
> or at the very least in the expectError message:

👍

**Comment by sindresorhus** [comment]
> or at the very least in the expectError message:

Do you plan to work on this? No pressure, but I need to know whether or not to release a new version after merging this.

**Comment by sindresorhus** [comment]
It would be too noisy to have the code on all diagnostics.

**Pull request merged**
